---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)

```

## Read in some data
Read in the litters dataset.

```{r}

pulse_df  =
  haven::read_sas("./data_import_examples/data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()

```


##Wide format to long formant

```{r}
pulse_tidy =
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi") %>% 
  relocate(id, visit) %>% 
  mutate(vist=recode(visit, "bl"="00m"))

pulse_tidy
```

##binding rows 
using lor data

Import each table

```{r}
fellowship_ring =
  readxl::read_excel("./data_import_examples/data_import_examples/LotR_Words.xlsx",range = "B3:D6") %>% 
  mutate(movie="fellowship_ring")

two_towers =
  readxl::read_excel("./data_import_examples/data_import_examples/LotR_Words.xlsx",range = "F3:H6") %>% 
  mutate(movie="two_towers")

return_king =
  readxl::read_excel("./data_import_examples/data_import_examples/LotR_Words.xlsx",range = "J3:L6") %>% 
  mutate(movie="return_king")

```

append
impor

```{r}
lotr_tidy=
  bind_rows(fellowship_ring,two_towers,return_king) %>%
  janitor::clean_names() %>% 
  pivot_longer(cols=female:male,
               names_to="sex",
               values_to="words")
               
  
```


##joining datasets
Import and clean both datasets
```{r}
litters_df <- read_csv("data_import_examples/data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  relocate(litter_number)

pups_df <- 
read_csv("data_import_examples/data_import_examples/FAS_pups.csv")%>% 
  janitor::clean_names() %>% 
  relocate(litter_number)
```

Joine
```{r}
fas_df=
  left_join(pups_df,litters_df,by = "litter_number")
```



